### API do Banco Central

https://dadosabertos.bcb.gov.br/dataset?res_format=API

In [38]:
import pandas as pd
import requests

In [ ]:
link = "https://olinda.bcb.gov.br/olinda/servico/mecir_dinheiro_em_circulacao/versao/v1/odata/informacoes_diarias?$top=10000&$orderby=Data%20desc&$format=json"

requisicao = requests.get(link)

informacoes = requisicao.json()

In [40]:
tabela = pd.DataFrame(informacoes['value'])

#tabela["Valor"] = tabela["Quantidade"].map("R${:,}".format)



display(tabela)

             Data  Quantidade         Valor Denominacao Especie
0      2026-10-06  3191004756  3.191005e+07        0.01  Moedas
1      2026-10-06  8485626345  4.242813e+08        0.05  Moedas
2      2026-10-06  8595378660  8.595379e+08        0.10  Moedas
3      2026-10-06  3921161888  9.802905e+08        0.25  Moedas
4      2026-10-06  3915998611  1.957999e+09        0.50  Moedas
...           ...         ...           ...         ...     ...
99995  1995-07-31  1047572990  1.047573e+07        0.01  Moedas
99996  1995-07-31   822911722  4.114559e+07        0.05  Moedas
99997  1995-07-31   764328301  7.643283e+07        0.10  Moedas
99998  1995-07-31   247216309  6.180408e+07        0.25  Moedas
99999  1995-07-31   402488315  2.012442e+08        0.50  Moedas

[100000 rows x 5 columns]

In [43]:
# pegar todas as informacoes com varias requisicoes

tabela_final = pd.DataFrame()
pular_texto = 0

while True:
    link2 = f"https://olinda.bcb.gov.br/olinda/servico/mecir_dinheiro_em_circulacao/versao/v1/odata/informacoes_diarias?$top=10000&$skip={pular_texto}&$orderby=Data%20desc&$format=json"
    requisicao2 = requests.get(link2)
    informacoes2 = requisicao2.json()
    tabela2 = pd.DataFrame(informacoes2['value'])
    if len (informacoes2['value']) < 1:
        break
    tabela_final = pd.concat([tabela_final,tabela2])
    pular_texto += 10000

display(tabela_final)

            Data  Quantidade         Valor Denominacao  Especie
0     2026-10-06  3191004756  3.191005e+07        0.01   Moedas
1     2026-10-06  8485626345  4.242813e+08        0.05   Moedas
2     2026-10-06  8595378660  8.595379e+08        0.10   Moedas
3     2026-10-06  3921161888  9.802905e+08        0.25   Moedas
4     2026-10-06  3915998611  1.957999e+09        0.50   Moedas
...          ...         ...           ...         ...      ...
2256  1994-10-03   181609358  1.816094e+08        1.00   Moedas
2257  1994-10-03   252922174  1.264611e+09        5.00  Cédulas
2258  1994-10-03   273630983  2.736310e+09       10.00  Cédulas
2259  1994-10-03    28945486  1.447274e+09       50.00  Cédulas
2260  1994-10-03     2841789  2.841789e+08      100.00  Cédulas

[102261 rows x 5 columns]

In [ ]:
link2 = "https://olinda.bcb.gov.br/olinda/servico/mecir_dinheiro_em_circulacao/versao/v1/odata/informacoes_diarias?$top=10000&$skip=100000000&$orderby=Data%20desc&$format=json"
requisicao2 = requests.get(link2)
informacoes2 = requisicao2.json()

print(informacoes2)

{'@odata.context': 'https://was-p.bcnet.bcb.gov.br/olinda/servico/mecir_dinheiro_em_circulacao/versao/v1/odata$metadata#informacoes_diarias', 'value': []}